### ISSUE TITLE
The serializer throws an exception on a valid relative base value

### ISSUE THREAD

**Issue by rjyounes** [edmcouncil/rdf-toolkit#48]
Sample turtle:

```
@base  <file.ttl> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix ex: <https://example.com/> .

ex:Thing a owl:Class ;
    skos:prefLabel "Thing" ;
    .

```

Exception:

```
17:32:17.836 ERROR o.e.r.rio.helpers.ParseErrorLogger - [Rio fatal] Not a valid (absolute) IRI: /file.ttl (1, -1)
17:32:17.838 ERROR o.e.r.runner.RdfToolkitRunner - RdfFormatter: stopped by unexpected exception:
17:32:17.839 ERROR o.e.r.runner.RdfToolkitRunner - Unable to parse input file: /Users/ryounes/Projects/tol/models/test.ttl
17:32:17.839 ERROR o.e.r.runner.RdfToolkitRunner - Command line arguments: [-tfmt, turtle, -sdt, explicit, -dtd, -ibn, -s, test.ttl, -t, test.ttl.bak]
17:32:17.839 ERROR o.e.r.runner.RdfToolkitRunner - RDFParseException: Not a valid (absolute) IRI: /file.ttl [line 1]
17:32:17.840 ERROR o.e.r.runner.RdfToolkitRunner - org.eclipse.rdf4j.rio.RDFParseException: Not a valid (absolute) IRI: /file.ttl [line 1]
        at org.eclipse.rdf4j.rio.helpers.RDFParserHelper.reportFatalError(RDFParserHelper.java:373)
        at org.eclipse.rdf4j.rio.helpers.AbstractRDFParser.reportFatalError(AbstractRDFParser.java:772)
        at org.eclipse.rdf4j.rio.turtle.TurtleParser.reportFatalError(TurtleParser.java:1310)
        at org.eclipse.rdf4j.rio.helpers.AbstractRDFParser.createURI(AbstractRDFParser.java:424)
        at org.eclipse.rdf4j.rio.helpers.AbstractRDFParser.resolveURI(AbstractRDFParser.java:402)
        at org.eclipse.rdf4j.rio.turtle.TurtleParser.parseURI(TurtleParser.java:937)
        at org.eclipse.rdf4j.rio.turtle.TurtleParser.parseBase(TurtleParser.java:297)
        at org.eclipse.rdf4j.rio.turtle.TurtleParser.parseDirective(TurtleParser.java:216)
        at org.eclipse.rdf4j.rio.turtle.TurtleParser.parseStatement(TurtleParser.java:192)
        at org.eclipse.rdf4j.rio.turtle.TurtleParser.parse(TurtleParser.java:162)
        at org.eclipse.rdf4j.rio.turtle.TurtleParser.parse(TurtleParser.java:125)
        at org.eclipse.rdf4j.rio.Rio.parse(Rio.java:299)
        at org.eclipse.rdf4j.rio.Rio.parse(Rio.java:265)
        at org.eclipse.rdf4j.rio.Rio.parse(Rio.java:237)
        at org.edmcouncil.rdf_toolkit.runner.RdfToolkitRunner.readModel(RdfToolkitRunner.java:264)
        at org.edmcouncil.rdf_toolkit.runner.RdfToolkitRunner.runOnFile(RdfToolkitRunner.java:179)
        at org.edmcouncil.rdf_toolkit.runner.RdfToolkitRunner.run(RdfToolkitRunner.java:106)
        at org.edmcouncil.rdf_toolkit.RdfFormatter.run(RdfFormatter.java:64)
        at org.edmcouncil.rdf_toolkit.RdfFormatter.main(RdfFormatter.java:47)
Caused by: java.lang.IllegalArgumentException: Not a valid (absolute) IRI: /file.ttl
        at org.eclipse.rdf4j.model.impl.SimpleIRI.setIRIString(SimpleIRI.java:75)
        at org.eclipse.rdf4j.model.impl.SimpleIRI.<init>(SimpleIRI.java:64)
        at org.eclipse.rdf4j.model.impl.SimpleValueFactory.createIRI(SimpleValueFactory.java:102)
        at org.eclipse.rdf4j.rio.helpers.RDFStarDecodingValueFactory.createIRI(RDFStarDecodingValueFactory.java:42)
        at org.eclipse.rdf4j.rio.helpers.AbstractRDFParser.createURI(AbstractRDFParser.java:422)
        ... 15 more

```

This is valid Turtle, as you can see from the [Turtle grammar](https://www.w3.org/TR/turtle/#sec-grammar-grammar), so the serializer be able to parse it.

I am using the latest release of rdf-toolkit.jar, version 1.14.2.

**Comment by mereolog** [comment]
@rjyounes thanks for your comment - you are right that the example conforms to the Turtle grammar.
Still, I think you should raise it with https://github.com/eclipse/rdf4j because it is their module that does not accept @base  <file.ttl> .

Btw., by the definition in https://www.ietf.org/rfc/rfc3987.txt `file.ttl `is not a valid absolute IRI (because of the missing colon), so the _message_ produced by rdf4j is right. It cannot be a valid relative IRI reference as well because it defines a namespace's prefix.  
For the same reason https://www.w3.org/TR/turtle/#sec-parsing-terms seems wrong where it says that [IRIREF](https://www.w3.org/TR/turtle/#grammar-production-IRIREF) is a production rule for IRIs - it is not because it may produce invalid IRIs as in your example.
