### ISSUE TITLE
BNodeComparator error

### ISSUE THREAD

**Issue by justin2004** [edmcouncil/rdf-toolkit#56]
testcase1.ttl 
```turtle
@prefix ex: <https://ex.com/> .

_:b66 a ex:Execution ;
   ex:produces _:b67  .

_:b67 a ex:ContentExpression .
# _:b67 ex:a ex:ContentExpression .
```

```sh
$ java -jar rdf-toolkit-1.14.2.jar -tfmt turtle -sdt explicit -dtd -ibn -sni -s testcase1.ttl -t testoutput.ttl
```
produces:
```
14:35:52.273 ERROR o.e.rdf_toolkit.RdfFormatter - RdfFormatter: stopped by unexpected exception: 
14:35:52.274 ERROR o.e.rdf_toolkit.RdfFormatter - RDFHandlerException: unable to generate/write RDF output
14:35:52.275 ERROR o.e.rdf_toolkit.RdfFormatter - org.eclipse.rdf4j.rio.RDFHandlerException: unable to generate/write RDF output
        at org.edmcouncil.rdf_toolkit.writer.SortedTurtleWriter.endRDF(SortedTurtleWriter.java:179)
        at org.eclipse.rdf4j.rio.Rio.write(Rio.java:582)
        at org.edmcouncil.rdf_toolkit.runner.RdfToolkitRunner.runOnFile(RdfToolkitRunner.java:218)
        at org.edmcouncil.rdf_toolkit.runner.RdfToolkitRunner.run(RdfToolkitRunner.java:104)
        at org.edmcouncil.rdf_toolkit.RdfFormatter.run(RdfFormatter.java:64)
        at org.edmcouncil.rdf_toolkit.RdfFormatter.main(RdfFormatter.java:47)
Caused by: java.lang.NullPointerException
        at org.edmcouncil.rdf_toolkit.comparator.ComparisonUtils.isCollection(ComparisonUtils.java:138)
        at org.edmcouncil.rdf_toolkit.comparator.BNodeComparator.compareBlankNodesWithInlining(BNodeComparator.java:102)
        at org.edmcouncil.rdf_toolkit.comparator.BNodeComparator.compare(BNodeComparator.java:91)
        at org.edmcouncil.rdf_toolkit.comparator.ResourceComparator.compare(ResourceComparator.java:84)
        at org.edmcouncil.rdf_toolkit.comparator.ResourceComparator.compare(ResourceComparator.java:63)
        at org.edmcouncil.rdf_toolkit.comparator.ResourceComparator.compare(ResourceComparator.java:46)
        at java.base/java.util.TreeMap.put(TreeMap.java:550)
        at java.base/java.util.TreeSet.add(TreeSet.java:255)
        at java.base/java.util.AbstractCollection.addAll(AbstractCollection.java:352)
        at java.base/java.util.TreeSet.addAll(TreeSet.java:312)
        at org.edmcouncil.rdf_toolkit.model.UnsortedTurtleResourceList.toSorted(UnsortedTurtleResourceList.java:41)
        at org.edmcouncil.rdf_toolkit.writer.SortedTurtleWriter.endRDF(SortedTurtleWriter.java:169)
        ... 5 more
```

but if you move the comment to the line above it then it works.

**Comment by mereolog** [comment]
I think this should be fixed in https://github.com/edmcouncil/rdf-toolkit/releases/tag/v.1.15.

**Comment by justin2004** [comment]
thanks @mereolog .
can we cut a release with a .jar file?

**Comment by mereolog** [comment]
> thanks @mereolog .
> can we cut a release with a .jar file?

Yes, we will try to set this up next week.

**Comment by przemekgradzki** [comment]
Done [rdf-toolkit.jar](https://github.com/edmcouncil/rdf-toolkit/releases/download/v.1.15/rdf-toolkit.jar)
